name: End-to-end tests

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use your preferred Node.js version
      
      - name: Install npm dependencies
        run: npm install
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
      
      - name: Store Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      
      - name: Store Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
      
      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json
      
      - name: Extract Test Summary
        run: node update-summary.js
      
      - name: Update README.md
        run: |
          # Remove old summary and append new summary
          sed -i '/# Test Summary/,+10d' README.md || true
          cat SUMMARY.md >> README.md
          rm SUMMARY.md
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Update test summary in README.md'
          add: 'README.md'